
# PG CONNECTION COMMAND : psql api  -h pg-api.docker -U benoit -W

version: '2.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      DNSDOCK_ALIAS: pg-api.docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api

volumes:
  pgdata:
